name: Build and Push (Docker Hub)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  REGISTRY: docker.io
  IMAGE_NAME: comfyui-worker

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      # Free space BEFORE starting BuildKit to avoid restart loops
      - name: Pre-clean runner disk
        run: |
          sudo rm -rf /usr/local/lib/android || true
          sudo rm -rf /opt/ghc || true
          sudo rm -rf /usr/share/dotnet || true
          docker system prune -af || true
          docker builder prune -af || true

      # QEMU not needed if you only build amd64; drop it to reduce moving parts
      # - name: Set up QEMU
      #   uses: docker/setup-qemu-action@v3

      - name: Set up Buildx (fresh builder each run)
        uses: docker/setup-buildx-action@v3
        with:
          install: true
          cleanup: true
          driver-opts: |
            image=moby/buildkit:v0.13.1
          buildkitd-flags: --oci-worker-gc=true --oci-worker-gc-keepstorage=8GB

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: docker.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Derive tag
        id: meta
        run: |
          echo "TAG=v7.4" >> $GITHUB_OUTPUT

      - name: Build & Push (linux/amd64)
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          platforms: linux/amd64
          provenance: false
          sbom: false
          outputs: type=registry,compression=zstd,force-compression=true
          tags: docker.io/${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:${{ steps.meta.outputs.TAG }}
          cache-from: type=registry,ref=docker.io/${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:buildcache
          cache-to:   type=registry,ref=docker.io/${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:buildcache,mode=max

      - name: Post-clean docker
        if: always()
        run: |
          docker system prune -af || true
          docker builder prune -af || true
