name: Build and Push (Docker Hub)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

concurrency:
  group: build-${{ github.ref }}
  cancel-in-progress: true

env:
  IMAGE_NAME: comfyui-worker
  TAG: v7.7

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 1 }

      - name: Pre-clean runner disk
        run: |
          sudo rm -rf /usr/local/lib/android /usr/share/dotnet /opt/ghc || true
          docker system prune -af || true
          docker builder prune -af || true

      - name: Docker login
        uses: docker/login-action@v3
        with:
          registry: docker.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Build with the default docker engine (amd64 on GH runners)
      - name: Docker build
        env:
          DOCKER_BUILDKIT: "1"
        run: |
          docker build \
            --progress=plain \
            -t docker.io/${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:${{ env.TAG }} \
            -f Dockerfile .

      - name: Docker push
        run: |
          docker push docker.io/${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:${{ env.TAG }}

      - name: Cleanup docker
        if: always()
        run: |
          docker system prune -af || true