name: Reset Docker Builder (Emergency)

on:
  workflow_dispatch:

jobs:
  reset:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Free space (SDKs)
        run: |
          sudo rm -rf /usr/local/lib/android || true
          sudo rm -rf /usr/share/dotnet || true
          sudo rm -rf /opt/ghc || true

      - name: Diagnose disk
        run: |
          df -h
          docker system df || true

      - name: Kill and remove ALL containers (including wedged BuildKit)
        run: |
          docker ps -a || true
          docker stop $(docker ps -aq) 2>/dev/null || true
          docker rm -fv $(docker ps -aq) 2>/dev/null || true

      - name: Nuke buildx builders
        run: |
          docker buildx version
          docker buildx ls || true
          # remove all inactive builders
          docker buildx rm --all-inactive --force || true
          # remove a commonly used name if present
          docker buildx rm ci-builder || true

      - name: Prune Docker (images, layers, volumes)
        run: |
          docker builder prune -af || true
          docker system prune -af --volumes || true

      - name: Recreate clean builder
        run: |
          docker buildx create --name ci-builder --use \
            --driver docker-container \
            --driver-opt image=moby/buildkit:v0.13.1,network=host
          docker buildx inspect --bootstrap
          docker buildx ls
